language: node_js

node_js:
  - 16

services:
  - docker

script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy

  # Tagging
  - docker tag udagram-api-feed thaopth782/udagram-api-feed:v1
  - docker tag udagram-api-user thaopth782/udagram-api-user:v1
  - docker tag udagram-frontend thaopth782/udagram-frontend:v1
  - docker tag reverseproxy thaopth782/reverseproxy:v1

after_success:
  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thaopth782/udagram-api-feed:v1
  - docker push thaopth782/udagram-api-user:v1
  - docker push thaopth782/udagram-frontend:v1
  - docker push thaopth782/reverseproxy:v1
